flask_final/users/models.py
from flask import current_app
from flask_final import db, login_manager
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(30), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def get_reset_token(self, expires_sec=1800):
        """Gets token for confirming email

        input:
            arg1:optional expires sec(default is 1800 )
        output:
            a serializer token."""
        s = Serializer(current_app.config["SECRET_KEY"], expires_sec)
        return s.dumps({"user_id": self.id}).decode("utf-8")

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config["SECRET_KEY"])
        try:
            user_id = s.loads(token)["user_id"]
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return "user({0}, {1})".format(self.full_name, self.email)

flask_final/users/forms.py
# -*-Code UTF-8
"""
forms for user registering
contains 4 classes:
    SignupForm
    LoginForm
    RequestResetForm
    PasswordResetForm
"""

from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_final.users.models import User


class SignupForm(FlaskForm):
    """
    Form for signing up the user
    Attributes:
        full_name [str]: full name of user
        email [str]: email of the user
        password [password]: secret password
        confirm_password [password]: confirmed password
        submit [submit]: submit field
    Methods:
        validate_email(): checks if email is already registered
    """

    full_name = StringField(
        "Full Name", validators=[DataRequired(), Length(max=20, min=3)]
    )
    email = StringField("Email-address", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired(), Length(min=3)])
    confirm_password = PasswordField(
        "confirm password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign UP")

    def validate_email(self, email):
        """
        Checks if email is already registered and raises a
        ValidationError and flashes a warning if so
        """

        duplicate_user = User.query.filter_by(email=email.data).first()
        if duplicate_user:
            flash("Email already registered. try another", "warning")
            raise ValidationError("Email already registered. try another")


class LoginForm(FlaskForm):
    """
    Form for logging in the user
    Attributes:
        email [str]: email of the user
        password [password]: secret password
        remember [bool]: checkbox for whether to remember sessions
        submit [submit]: submit field
    """

    email = StringField("Email-address", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired(), Length(min=3)])
    remember = BooleanField("Remember me")
    submit = SubmitField("Log in")


class RequestResetForm(FlaskForm):
    """
    Form for the user to request his passowrd reset
    Attributes:
        email [str]: email of the user
        submit [submit]: submit field
    Methods:
        validate_email(): checks if email is registered
    """

    email = StringField("Email-address", validators=[DataRequired(), Email()])
    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        """
        Checks for the given email in database
        raises ValidationError and flashes waring if not found
        """

        registered_user = User.query.filter_by(email=email.data).first()
        if registered_user is None:
            flash("Email not registered. try another", "warning")
            raise ValidationError("Email not registered. try another")


class PasswordResetForm(FlaskForm):
    """
    Form for reseting the user's password
    Attributes:
        password [password]: secret password
        confirm_password [password]: confirmed password
        submit [submit]: submit field
    """

    password = PasswordField("password", validators=[DataRequired(), Length(min=3)])
    confirm_password = PasswordField(
        "confirm password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Reset")

flask_final/__init__.py
# -*-code: UTF-8
"""
Initialization module of projects that initializes
app, db, Kbdlog,bcrypt, login_manager, mail, Config

"""
import json
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail

bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
db = SQLAlchemy()
mail = Mail()
NEWS_API_KEY = os.getenv("NEWS_API_KEY")


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from flask_final.users.routes import users
    from flask_final.newslet.routes import newslet
    from flask_final.main.routes import main

    app.register_blueprint(users)
    app.register_blueprint(newslet)
    app.register_blueprint(main)

    return app

flask_final/main/routes.py
"""
contains core routes of webapp
"""

from flask import render_template, redirect, Blueprint, url_for
from flask_login import current_user

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    # if current_user.is_authenticated:
    return redirect(url_for("newslet.nep_national_news"))
    # return redirect(url_for("newslet.eng_international_news"))


@main.route("/home", methods=["GET", "POST"])
def homepage():
    return render_template("home.html")


@main.route("/about", methods=["GET"])
def about():
    return render_template("about.html", title="About this website")


@main.route("/privacy_policy", methods=["GET"])
def privacy_policy():
    return render_template("privacy_policy.html", title="Privacy policy")

flask_final/newslet/__init__.py
# parser = 'lxml'
parser = "html.parser"

flask_final/newslet/routes.py
# -*-code; UTF_8
"""
Contains routes for managing news.
    news(): Mix collech 3 samples
    Detail news routes
        nep_national_news()
        nep_international_news()
        eng_national_news()
        eng_international_news()
"""

from flask import Blueprint
from flask import request, render_template
from flask_login import login_required, current_user
from flask_final.newslet.models import NepNationalNews as NNN
from flask_final.newslet.models import NepInternationalNews as NIN
from flask_final.newslet.models import EngNationalNews as ENN
from flask_final.newslet.models import EngInternationalNews as EIN
from flask_final.newslet.news_loader import load_news_to_models

newslet = Blueprint("newslet", __name__)


@newslet.route("/dashboard/news", methods=["GET"])
@newslet.route("/dashboard/news/nep/national", methods=["GET"])
def nep_national_news():
    """
    Save extracted news from scraper to db model
    then passes to detail_news.html template to render it
    """

    load_news_to_models("NNN")
    page = request.args.get("page", 1, type=int)
    free_sources = ("ujyaalo_online", "hamra_kura")
    news = None
    logged = current_user.is_authenticated
    if not logged:
        for source in free_sources:
            if not news:
                news = NNN.query.filter_by(source=source)
            else:
                news = news.union(NNN.query.filter_by(source=source))

    else:
        news = NNN.query.order_by(NNN.date.desc())

    news = news.order_by(NNN.date.desc())
    news_list = news.paginate(page=page, per_page=15)
    return render_template(
        "detail_news.html",
        title="National-Nep",
        news_list=news_list,
        heading="National News [नेपा]",
        newslet_func="newslet.nep_national_news",
        read_more="|थप पढ्नुहोस >>|",
        logged=logged,
    )


@newslet.route("/dashboard/news/nep/international", methods=["GET"])
@login_required
def nep_international_news():
    """
    Save extracted news from scraper to db model
    then passes to detail_news.html template to render it
    """

    load_news_to_models("NIN")
    page = request.args.get("page", 1, type=int)
    news_list = NIN.query.order_by(NIN.date.desc()).paginate(page=page, per_page=15)
    return render_template(
        "detail_news.html",
        title="International-Nep",
        news_list=news_list,
        heading="International News [नेपा]",
        newslet_func="newslet.nep_international_news",
        read_more="|थप पढ्नुहोस >>|",
        logged=True,
    )


@newslet.route("/dashboard/news/eng/national", methods=["GET"])
def eng_national_news():
    """
    Save extracted news from scraper to db model
    then passes to detail_news.html template to render it
    """
    load_news_to_models("ENN")
    page = request.args.get("page", 1, type=int)
    free_sources = ("himalayan_times", "nepali_times")
    news = None
    logged = current_user.is_authenticated
    if not logged:
        for source in free_sources:
            if not news:
                news = ENN.query.filter_by(source=source)
            else:
                news = news.union(ENN.query.filter_by(source=source))

    else:
        news = ENN.query.order_by(ENN.date.desc())

    news = news.order_by(ENN.date.desc())
    news_list = news.paginate(page=page, per_page=15)
    return render_template(
        "detail_news.html",
        title="National-Eng",
        news_list=news_list,
        heading="National News [Eng]",
        newslet_func="newslet.eng_national_news",
        read_more="|Read More>>|",
        logged=logged,
    )


@newslet.route("/dashboard/news/eng/international", methods=["GET"])
def eng_international_news():
    """
    Save extracted news from scraper to db model
    then passes to detail_news.html template to render it
    """
    load_news_to_models("EIN")
    load_news_to_models("NNN")
    load_news_to_models("ENN")
    page = request.args.get("page", 1, type=int)
    news_list = EIN.query.order_by(EIN.date.desc()).paginate(page=page, per_page=15)
    logged = current_user.is_authenticated
    return render_template(
        "detail_news.html",
        title="International-Eng",
        news_list=news_list,
        heading="International News [Eng]",
        newslet_func="newslet.eng_international_news",
        read_more="|Read More>>|",
        logged=logged,
    )


@newslet.route("/update", methods=["GET"])
def update():
    categories = ("EIN", "NIN", "ENN")
    for category in categories:
        try:
            load_news_to_models(category)
        except Exception as E:
            print(E)

    return "<h1>Updated all news sources</h1>"

flask_final/users/routes.py
"""
contains resource for managing users functionality.
"""
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_user, logout_user, current_user, login_required
from flask_mail import Message
from flask_final import bcrypt, db, mail
from flask_final.users.forms import (
    SignupForm,
    LoginForm,
    RequestResetForm,
    PasswordResetForm,
)
from flask_final.users.models import User


users = Blueprint("users", __name__)


@users.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("newslet.nep_national_news"))
    form = SignupForm()
    if form.validate_on_submit():
        flash("Your account is created", "success")
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            full_name=form.full_name.data,
            email=form.email.data,
            password=hashed_password,
        )

        db.session.add(user)
        db.session.commit()
        return redirect(url_for("users.login"))

    return render_template("signup.html", title="Sign Up", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("newslet.nep_national_news"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            allowed_emails = ["try@try.com"]
            if user.email in allowed_emails:
                login_user(user, remember=form.remember.data)
            return redirect(url_for("newslet.nep_national_news"))
        else:
            flash("Invalid email or password. Try again!", "info    ")
            return redirect(url_for("users.login"))
    return render_template("login.html", title="Log in", form=form)


@users.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("newslet.nep_national_news"))


@users.route("/password/reset", methods=["GET", "POST"])
def reset_request():
    form = RequestResetForm()
    if form.email.data == "try@try.com":
        flash("Invalid request. This is public try account", "warning")

    elif form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_mail(user)
        flash("Email with reset link is sent. Check your email!", "success")
        if current_user.is_authenticated:
            return redirect(url_for("users.reset_request"))
        else:
            return redirect(url_for("users.login"))

    return render_template("reset_request.html", titile="Reset password", form=form)


@users.route("/password/reset/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        flash("Logout and change your password.", "info")
        return redirect(url_for("newslet.nep_national_news"))

    user = User.verify_reset_token(token)
    if user is None:
        flash("Invalid or expired token!", "warning")
        return redirect(url_for("users.reset_request"))
    form = PasswordResetForm()
    if form.validate_on_submit():
        flash("Your password has been succesfully updated! Login now. ", "success")
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        return redirect(url_for("users.login"))

    return render_template("reset_password.html", title="Password reset", form=form)


def send_reset_mail(user):
    token = user.get_reset_token()
    msg = Message(
        "Reset Password for Khabar Board",
        sender="noreply@demo.com",
        recipients=[user.email],
    )
    msg.html = render_template(
        "reset_password_email.html",
        user=user,
        action_url=url_for("users.reset_token", token=token, _external=True),
    )
    mail.send(msg)

flask_final/templates/about.html
{%extends 'dashboard.html'%}

{%block content%}

<div class="container">

    <a href='{{url_for('main.about')}}'>
        <h1>
            About this website
        </h1>
    </a>

    <p class="text-justify">
        This website is built as the pet project of mine. On the journey to learn backend web-development, I decided to
        make something of my own interest to practice my skills.
    </p>

    <p class="text-justify">
        Khabar-board currently featured extracted summary news from various news portals of Nepal. Similarly, We will
        soon incorporate news from top international sites as well. Similarly, handy tools like conversion tools,
        weather and other facilities are also on the way.
    </p>

    <br><br>

    <p>
        I am also planning to include push notificatiion and newsletters in the future.
    </p>

    <br>
    <div class="mb-5">
        <button class='btn btn-info'>
            <a href="{{url_for('newslet.eng_international_news')}}">
                Back to dashboard
            </a>
        </button>
    </div>

</div>
{%endblock content%}

flask_final/templates/dashboard.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% if title %}
    <title id='title'>{{title}}</title>
    {% else %}
    <title>Dashboard | Khabar-board</title>
    {%endif %}

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Our Custom CSS -->

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='dashboard/dashboard.css')}}">
    <link rel="icon" type="image/png/jpg" href="{{url_for('static',filename='images/icon.jpg')}}">
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div id="dismiss">
                <i class="glyphicon glyphicon-arrow-left"></i>
            </div>

            <div class="sidebar-header">
                <img class="img-responsive" style="width:3em;" src={{url_for('static',filename='images/icon.jpg')}}>
            </div>

            <ul class="list-unstyled components">
                <p>Dashboard</p>
                <li class="#">
                    <a id='sidebar_home' href="{{url_for('newslet.nep_national_news')}}">Home</a>
                <li>
                    <a id='about' href="{{url_for('main.about')}}">About</a>

                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">News
                    </a>

                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li><a id='sidebar_NNN' href="{{url_for('newslet.nep_national_news')}}">National(नेपा)</a></li>

                        <li><a id='sidebar_ENN' href="{{url_for('newslet.eng_national_news')}}">National(Eng)</a></li>

                    {% if logged %}
                        <li><a id='sidebar_NIN' href="{{url_for('newslet.nep_international_news')}}">International(नेपा)</a></li>
                    {% endif %}

                        <li><a id='sidebar_EIN' href="{{url_for('newslet.eng_international_news')}}">International(Eng)</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{{url_for('main.privacy_policy')}}">Privacy Policy</a>
                </li>

            </ul>

            <ul class="list-unstyled CTAs">
            {% if logged %}
                <li><a href="{{url_for('users.logout')}}" class="download"><i class="glyphicon glyphicon-off"></i>
                        Logout</a></li>
            {% else %}
                <li><a href="{{url_for('users.login')}}" class="download"><i class="glyphicon glyphicon-off"></i>
                        Login</a></li>
 
            {% endif %}
            </ul>

        </nav>
        </div>

        <!-- Page Content Holder -->
        <div id="content">
            <nav class=" navbar navbar-default">
                <div class="container-fluid">

                    <div class="navbar-header">
                        <button type="button" id="sidebarCollapse" class=" btn btn-info navbar-btn">
                            <i class=" glyphicon glyphicon-align-left"></i>
                            Menu
                        </button>
                    </div>

                    <div class='dark_switch'>
                    <!-- Dark mode switch -->
                        <label>
                            <input id='dark_check' type="checkbox">
                            <span class="dark_slider round"></span>
                        </label>
                        <div id='dark_label'>Dark mode</div>

                    </div>

                </div>
            </nav>




            {%block content%}
            {% with messages = get_flashed_messages(with_categories = True)%}
            {%if messages%}
            {%for category,message in messages%}
            <br><br>
            <div class="alert alert-{{category}}">{{message}}</div>
            {%endfor%}
            {%endif%}
            {%endwith%}

            {%endblock content%}
        </div>

        <div class="overlay"></div>


        <script>
            window.onscroll = function() {responsiveNewsSidebar()};

            var news_menu = document.getElementsByClassName("news_menu")[0];
            var sticky = news_menu.offsetTop;
            var width = (window.innerWidth > 0) ? window.innerWidth : screen.width;
            var media_query = window.matchMedia("(min-width: 768px)")

            function responsiveNewsSidebar() {
              if (window.pageYOffset > sticky && media_query.matches) {
                news_menu.classList.add("sticky");
              } else {
                news_menu.classList.remove("sticky");
              }
            }
            media_query.addListener(responsiveNewsSidebar)
        </script>

        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#sidebar").mCustomScrollbar({
                    theme: "minimal"
                });

                $('#dismiss, .overlay').on('click', function () {
                    $('#sidebar').removeClass('active');
                    $('.overlay').fadeOut();
                });

                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').addClass('active');
                    $('.overlay').fadeIn();
                    $('.collapse.in').toggleClass('in');
                    $('a[aria-expanded=true]').attr('aria-expanded', 'false');
                });
            });

        </script>

        <script>

            var dark_mode = localStorage.getItem('dark_mode') 
            if(dark_mode == "true"){
               $('#dark_check').prop('checked', true);
               dark_on();
            }
            else {
               $('#dark_check').prop('checked', false);
               dark_off();
            }


            function dark_on() {
                $('* > :not(script)').css('background-color', 'black');
                $('* > :not(script)').css('color', 'lightgrey');
                localStorage.setItem('dark_mode', 'true')
            }

            function dark_off() {
                $('* > :not(script)').removeAttr('style');
                localStorage.setItem('dark_mode', 'false')
            }

            $('#dark_check').change(function() {
                if(this.checked) {
                    dark_on();
                }
                else {
                    dark_off();
                }

            });


    </script>
</body>

</html>

flask_final/templates/home.html
{%extends 'layout.html' %}

{%block content%}


<!--Bg-img-->
<div id="intro" style="background: url({{url_for('static', filename="images/lake.jpg")}}) no-repeat center;background-size: cover;">
    <div class="text-center pt-3" id="subi" style="color:white; ">
        <h3>Khabar Board <br>Get informed, Get smart</h3>
        <div class="pt-4">
            <h5 style="color:black;">It's Free and always will be!</h5>
            <a href="{{url_for('users.login')}}"><button class="btn btn-default btn-lg" id="button">login</button></a>
            <h5>Try without Signup?</h5>
            <a href="{{url_for('main.home')}}"><button class="btn btn-default btn-lg" id="button">Try</button></a>
        </div>
    </div>
</div>



<!--Main Content


<!--Main Content

-->
<div>

    <!-- Card 1-->
    <div class="card card-image" style="background-image: url({{url_for('static',filename='images/papers.jpeg')}});">

        <!-- Content -->
        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
            <div class="container-fluid row">

                <!--<h5 class="pink-text "><i class="fa fa-pie-chart"></i> Marketing</h5>-->
                <h3 class="card-title pt-2 col-12"><strong>News That Matters.</strong></h3>
                <div class="container text-center">
                    <p class="col-12">Latest, important and summarized national and international news right on your finger Tips.</p>
                </div>

            </div>
        </div>
        <!-- Content -->
    </div>
    <!-- Card -->

    <!-- Card 2-->
    <div class="card card-image" style="background-image: url({{url_for('static',filename='images/news_sources.jpeg')}});">

        <!-- Content -->
        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
            <div class="container-fluid row">

                <h3 class="card-title pt-2 col-md-12"><strong>Diverse and Trust worthy sources.</strong></h3>
                <div class="container">
                    <p class="col-md-12">We bring you news from reputed and established national and international news agencies. Our default news sources comprise BBC, CNN, The himalayan times, and Kantipur.</p>
                </div>

            </div>
        </div>
        <!-- Content -->
    </div>
    <!-- Card 2-->

    <!-- Card 3-->
    <div class="card card-image" style="background-image: url({{url_for('static',filename='images/dashboard.jpg')}});">

        <!-- Content -->
        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
            <div class="container-fluid row">

                <h3 class="card-title pt-2 col-md-12"><strong>Customize your dashboard.</strong></h3>
                <div class="container">
                    <p class="col-md-12">Pick your own topics, sources to filter your interest. Get live score updates of your favorite sports. Get updates about film releases, shows. So what are you waiting for?</p>
                </div>

            </div>
        </div>
        <!-- Content -->
    </div>
    <!-- Card 3-->


    <!-- Card 4-->
    <div class="card card-image mb-1" style="background-image: url({{url_for('static',filename='images/tools.jpeg')}});">

        <!-- Content -->
        <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
            <div class="container-fluid row">

                <h3 class="card-title pt-2 col-md-12"><strong>Wide range of Handy tools</strong></h3>
                <div class="container">
                    <p class="col-md-12">We bring you small handy tools like weather reports, conversion tools, calendar etc.</p>
                </div>

            </div>
        </div>
        <!-- Content -->
    </div>
    <!-- Card4 -->


</div>




{%endblock%}

flask_final/templates/login.html
{%extends 'layout.html'%}

{%block content%}
<br><br><br>


<!-- Material form login -->
<form method="POST" action="">
    {{form.hidden_tag()}}
    <fieldset>
        <p class="h4 text-center mb-4">Log in</p>

        <!-- Material input email -->
        {%if form.email.errors%}
        <div class="md-form">
            <i class="fa fa-envelope prefix grey-text"></i>
            {{form.email(type="email", id="materialFormLoginEmailEx", class="form-control")}}
            {{form.email.label(for="materialFormLoginEmailEx")}}

            {%for error in form.email.errors%}
            <span>{{error}}</span>
        </div>
        {%endfor%}
        {%else%}
        <div class="md-form">
            <i class="fa fa-envelope prefix grey-text"></i>
            {{form.email(type="email", id="materialFormLoginEmailEx", class="form-control")}}
            {{form.email.label(for="materialFormLoginEmailEx")}}
        </div>
        {%endif%}
        <!-- Material input password -->
        {%if form.password.errors %}
        <div class="md-form">
            <i class="fa fa-lock prefix grey-text"></i>
            {{form.password(type="password", id="materialFormLoginPasswordEx", class="form-control")}}
            {{form.password.label(for="materialFormLoginPasswordEx")}}

            {%for error in form.password.errors%}
            <p>{{error}}</p>
        </div>
        {%endfor%}
        {%else%}
        <div class="md-form">
            <i class="fa fa-lock prefix grey-text"></i>
            {{form.password(type="password", id="materialFormLoginPasswordEx", class="form-control")}}
            {{form.password.label(for="materialFormLoginPasswordEx")}}
        </div>
        {%endif%}
        <div class="mt-4 ml-4 form-check">
            {{form.remember(class="form-check-input")}}
            {{form.remember.label(class="form-check-label")}}
        </div>
        <div class="text-center mt-4">
            {{form.submit(class="btn btn-default")}}
        </div>
        <!--Footer-->
        <div class="modal-footer">
            <div class="options text-right">
                <p class="pt-1">Forgot your password? <a href="{{url_for('users.reset_request')}}" class="blue-text">Reset</a></p>

                <button class="btn btn-info"><a href="{{url_for('main.home')}}">Back</a></button>
            </div>
            <!--/.Panel 8-->
        </div>
    </fieldset>
</form>
<!-- Material form login -->
<br>


{%endblock content%}

flask_final/templates/reset_request.html
{%extends 'layout.html'%}

{%block content%}
<br><br><br><br>


<!-- Material form login -->
<form method="POST" action="">
    {{form.hidden_tag()}}
    <fieldset>
        <p class="h4 text-center mb-4">Request reset</p>

        <!-- Material input email -->
        {%if form.email.errors%}
        <div class="md-form">
            <i class="fa fa-envelope prefix grey-text"></i>
            {{form.email(type="email", id="materialFormLoginEmailEx", class="form-control")}}
            {{form.email.label(for="materialFormLoginEmailEx")}}

            {%for error in form.email.errors%}
            <span>{{error}}</span>
        </div>
        {%endfor%}
        {%else%}
        <div class="md-form">
            <i class="fa fa-envelope prefix grey-text"></i>
            {{form.email(type="email", id="materialFormLoginEmailEx", class="form-control")}}
            {{form.email.label(for="materialFormLoginEmailEx")}}
        </div>
        {%endif%}
        <!-- Material input password -->

        <div class="text-center mt-4">
            {{form.submit(class="btn btn-default")}}
        </div>
        <!--Footer-->
        <div class="modal-footer">
            <div class="options text-right">
                <p class="pt-1">Don't have an account yet? <a href="{{url_for('users.signup')}}" class="blue-text">Sign up</a></p>
                <button class="btn btn-info"><a href="{{url_for('main.home')}}">Back</a></button>
            </div>
            <!--/.Panel 8-->
        </div>
    </fieldset>
</form>
<!-- Material form login -->
<br>


{%endblock content%}